### ISSUE TITLE
Autoprefixes for dynamic / interpolated styles

### ISSUE THREAD

**Issue by ivan-kleshnin** [vercel/styled-jsx#795]
```tsx
import * as React from "react"

export default function Test() {
  const test2Styles = `
    display: flex;
    flex-wrap: wrap;
  `

  return <div>
    <div className="test-1">
      test-1
    </div>

    <div className="test-2">
      test-2
    </div>

    <style jsx>{`
      .test-1 {
        display: flex;
        flex-wrap: wrap;
      }
      
      .test-2 {
        ${test2Styles}
      }
    `}</style>
  </div>
}
```

Both `test-1` and `test-2` get correct CSS styles.
Hovewer only styles of `test-1` are autoprefixed.

#### test-1

```css
.test-1.jsx-2690212892 {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

#### test-2

```css
.test-2.jsx-2690212892 {
    display: flex;
    flex-wrap: wrap;
}
```

I currently use `https://github.com/robinweser/inline-style-prefixer` to workaround the issue.
Does Vercel Team consider it a missing feature or it's omitted intentionally?
