### ISSUE TITLE
adjacent sibling combinator(+) override nth-child styles

### ISSUE THREAD

**Issue by iamsungjinkim** [vercel/styled-jsx#798]
#### Do you want to request a _feature_ or report a _bug_?
a bug

#### What is the current behavior?
```css
  li + li {
    margin: 0;
  }

  li:nth-child(2n) {
    margin-left: 4.68%;
  }

  li:nth-child(3),
  li:nth-child(4) {
    margin-top: 4.68%;
  }
```

expected
- reset `li` tags(from 2th) to `margin: 0`
- override `margin-left`, `margin-top` with `nth-child` styles

actual
- `li` tags(from 2th) have `margin: 0`
- and ignore `nth-child` styles

#### Environment (include versions)

- Version of styled-jsx (or next.js if it's being used): 5.0.2
- Browser: chrome
- OS: mac
