### ISSUE TITLE
Scope type not being changed when using comment on external file

### ISSUE THREAD

**Issue by lgmf** [vercel/styled-jsx#827]
#### Do you want to request a _feature_ or report a _bug_? 

report a _bug_

#### What is the current behavior?

The type is being ignored when set per individual CSS file via CSS comment like `/* @styled-jsx=<type>*/` when using custom babel and webpack config.

This happens only for the production build (it works in dev mode).

#### What is the expected behavior?

Set the scope type per CSS file when it has a comment with `/* @styled-jsx=<type> */`

#### Environment

- Version: next@11, node@14.19,3, npm@6.14.17
- Browser: Chrome
- OS: Mac

Basically, I have this style that's supposed to be global

```scss
/* @styled-jsx=global */
*,
*::before,
*::after {
  box-sizing: border-box;
  font-family: "Roboto", sans-serif;
}

body {
  margin: 0;
}

p {
  font-size: 48px;
  font-weight: bold;
}
```

- On Dev:
![Screenshot 2023-03-02 at 17 13 35](https://user-images.githubusercontent.com/8532045/222541765-af0beba1-6e7b-4808-b200-255bb454d7d5.png)

- On Prod:
![Screenshot 2023-03-02 at 17 14 37](https://user-images.githubusercontent.com/8532045/222541934-e799fc02-a816-4c60-bb67-f7f7eceb962a.png)

Here's the link to the sample project to reproduce the bug: https://github.com/lgmf/next-styled-jsx-global-bug

#### Did this work in previous versions?
Yes
